# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[('gui', 'gui')],
    hiddenimports=[
        'PyQt6.QtCore',
        'PyQt6.QtGui', 
        'PyQt6.QtWidgets',
        'gui.main_window',
        'gui.schedule_tab',
        'gui.people_tab',
        'gui.courses_tab',
        'gui.common_times_tab',
        'gui.time_picker'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'tkinter',
        'matplotlib',
        'numpy',
        'pandas',
        'scipy',
        'PIL',
        'cv2',
        'tensorflow',
        'torch',
        'jupyter',
        'notebook',
        'IPython',
        'sphinx',
        'pytest',
        'unittest',
        'doctest',
        'pdb',
        'profile',
        'pstats',
        'cProfile',
        'trace',
        'distutils',
        'setuptools',
        'pip',
        'wheel',
        'pkg_resources',
        'email',
        'http',
        'xml',
        'sqlite3',
        'multiprocessing',
        'concurrent',
        'asyncio',
        'socket',
        'ssl',
        'hmac',
        'secrets',
        'uuid',
        'gzip',
        'bz2',
        'lzma',
        'tarfile',
        'mimetypes',
        'platform',
        'subprocess',
        'shlex',
        'signal',
        'curses',
        'readline',
        'rlcompleter',
        'tabnanny',
        'pyclbr'
    ],
    noarchive=False,
    optimize=2,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ScheduleManager',
    debug=False,
    bootloader_ignore_signals=False,
    strip=True,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
app = BUNDLE(
    exe,
    name='ScheduleManager.app',
    icon=None,
    bundle_identifier='com.schedulemanager.app',
    info_plist={
        'CFBundleName': 'Schedule Manager',
        'CFBundleDisplayName': 'Schedule Manager',
        'CFBundleIdentifier': 'com.schedulemanager.app',
        'CFBundleVersion': '2.0.4',
        'CFBundleShortVersionString': '2.0.4',
        'CFBundleExecutable': 'ScheduleManager',
        'CFBundlePackageType': 'APPL',
        'CFBundleSignature': '????',
        'LSMinimumSystemVersion': '10.15.0',
        'NSHighResolutionCapable': True,
    },
)
