[project]
name = "scheduler"
version = "2.0.4"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyinstaller>=6.15.0",
    "pyqt6>=6.9.1",
    "cryptography>=46.0.0",
]
